name: Run Solidity Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v2.3.4

    - name: Cache Compiler Installations
      uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '14'

    - name: Install Truffle
      run: npm install -g truffle@5.1.53

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.1

    - name: Install Dependencies
      run: npm i

    - name: Run Ganache
      run: ganache-cli &

    - name: Run Truffle Tests
      run: truffle test
